### ISSUE TITLE
Replace underscore

### ISSUE THREAD

**Issue by merlinstardust** [aldeed/meteor-schema-index#14]
Along with the [collection2-core issue](https://github.com/aldeed/meteor-collection2-core/issues/39) I just submitted, this package will need underscore replaced as well.

Only one line here to replace

```
47:  _.each(ss[propName](), function(definition, fieldName) {
```

**Comment by lhz516** [comment]
Meteor core modules are also using underscore. What is the point to replace it?

**Comment by merlinstardust** [comment]
It's possible to use Meteor and not have underscore on the client side at all. By replacing underscore, the client side load can become lighter.

**Comment by merlinstardust** [comment]
Does anything else need to be done to get PR #15 merged in?
